version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventario_dw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: inventario_dw
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db

volumes:
  pgdata:
