# Generated by Django 5.2.3 on 2025-06-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mes', models.IntegerField()),
                ('trimestre', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='DimProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('tipo_tienda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HechosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad_vendida', models.IntegerField()),
                ('cantidad_reabastecida', models.IntegerField()),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimfecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimproducto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimproveedor')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimtienda')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
