# Generated by Django 5.2.3 on 2025-06-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimtienda',
            name='direccion',
            field=models.TextField(default='Sin dirección'),
        ),
        migrations.AlterField(
            model_name='dimfecha',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
